### ISSUE TITLE
token exposed?

### ISSUE THREAD

**Issue by lordmen99** [huangpd/midjourney_api#1]
hi nice script, but i see to submit to api, its expose the token from mj. its to risk i think

**Comment by lordmen99** [comment]
oh ok got it

**Comment by lordmen99** [comment]
btw, you know. mj now have captcha active. how prevent this, i mean how our submit generate not meet this captcha

**Comment by huangpd** [comment]
> 顺便说一句，你知道的。MJ 现在激活了验证码。如何防止这种情况，我的意思是我们的提交生成如何不符合这个验证码

I don't know

**Comment by lordmen99** [comment]
any demi web use this api?
