### ISSUE TITLE
无法生成token

### ISSUE THREAD

**Issue by dxcbl008** [huangpd/midjourney_api#3]
![微信图片_20230526145023](https://github.com/huangpd/midjourney_api/assets/131538604/ef0956e3-7912-40a8-b652-34e1a043ca73)

**Comment by huangpd** [comment]
查看数据库users_token表



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dxcbl008 ***@***.***&gt;
发送时间: 2023年5月26日 14:51
收件人: huangpd/midjourney_api ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [huangpd/midjourney_api] 无法生成token (Issue #3)
