### ISSUE TITLE
很多问题，建议readme写详细点

### ISSUE THREAD

**Issue by ItManner** [huangpd/midjourney_api#5]
换了redis，数据库拿到了token，去请求创建图片任务接口
报错导致程序停止
![1685516186420](https://github.com/huangpd/midjourney_api/assets/133472049/c10ab7a1-5533-42f7-bdb9-ad48bf56e395)
不知道是不是proxy为空的原因导致的？但是我部署到服务器的我也不需要设置代理啊
![1685516236053](https://github.com/huangpd/midjourney_api/assets/133472049/ecb37386-3d1f-4df5-adf8-356dc6faded6)

**Comment by huangpd** [comment]
> 换了redis，数据库拿到了token，去请求创建图片任务接口 报错引导程序停止 不知道是不是proxy为空的原因导致的？但我部属到服务器的我也不需要设置代理啊 ![1685516186420](https://user-images.githubusercontent.com/133472049/242185784-c10ab7a1-5533-42f7-bdb9-ad48bf56e395.png) ![1685516236053](https://user-images.githubusercontent.com/133472049/242185992-ecb37386-3d1f-4df5-adf8-356dc6faded6.png)

channel id要不相同
